###
POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 890000,
    "make": "toyota",
    "model": "sienta",
    "year": 2020,
    "lng": 0,
    "lat": 0,
    "mileage": 10000
}

###
PATCH http://localhost:3000/reports/16
Content-Type: application/json

{
    "approved": false
}