###

GET http://localhost:3000/reports?make=tesla&model=model x&lng=0&lat=0&mileage=10000&year=2020


###
POST http://localhost:3000/reports
Content-Type: application/json

{
    "price": 890000,
    "make": "tesla",
    "model": "model x",
    "year": 2023,
    "lng": 0,
    "lat": 0,
    "mileage": 30000
}

###
PATCH http://localhost:3000/reports/22
Content-Type: application/json

{
    "approved": true
}